In [110]:
import pandas as pd

In [111]:
all_data = pd.read_csv('norm_data.csv',index_col=0)

In [112]:
all_data

,name,price,NFC,Color,Диагональ,RAM,Память,Емкость акк,rating,reviews,OS,Тип экрана_IPS,Тип экрана_OLED,Тип экрана_Other
0,181,78990,0,21,5.500,2.0,64.0,2600.0,0.0,0,0,True,False,False
1,181,79000,0,16,5.500,2.0,64.0,2600.0,0.0,0,0,True,False,False
2,182,47990,0,21,5.000,2.0,16.0,2000.0,0.0,0,0,True,False,False
3,182,53550,0,16,5.000,2.0,16.0,2000.0,0.0,0,0,True,False,False
4,173,129990,1,12,6.500,8.0,256.0,10000.0,4.9,10,0,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3031,188,99000,1,21,6.790,8.0,256.0,5000.0,5.0,10,0,True,False,False
3032,188,79000,1,7,6.790,6.0,128.0,5000.0,4.7,10,0,True,False,False
3033,187,54900,0,16,6.517,4.0,64.0,4500.0,0.0,0,0,True,False,False
3034,187,59000,0,16,6.517,4.0,128.0,4500.0,0.0,0,0,True,False,False
3035,187,54900,0,21,6.517,4.0,64.0,4500.0,0.0,0,0,True,False,False

### *Linear Regression*

In [113]:
y = all_data['price']
X = all_data.drop('price', axis=1)
#predict the price

In [114]:
X.head(10)

,name,NFC,Color,Диагональ,RAM,Память,Емкость акк,rating,reviews,OS,Тип экрана_IPS,Тип экрана_OLED,Тип экрана_Other
0,181,0,21,5.50,2.0,64.0,2600.0,0.0,0,0,True,False,False
1,181,0,16,5.50,2.0,64.0,2600.0,0.0,0,0,True,False,False
2,182,0,21,5.00,2.0,16.0,2000.0,0.0,0,0,True,False,False
3,182,0,16,5.00,2.0,16.0,2000.0,0.0,0,0,True,False,False
4,173,1,12,6.50,8.0,256.0,10000.0,4.9,10,0,True,False,False
5,179,1,21,4.30,8.0,256.0,3880.0,4.9,1,0,True,False,False
6,165,1,21,6.50,12.0,256.0,4380.0,4.8,1,0,True,False,False
7,159,1,21,6.67,12.0,256.0,5050.0,4.8,2,0,False,False,False
8,159,1,20,6.67,12.0,256.0,5050.0,4.8,1,0,False,False,False
9,160,0,21,6.50,2.0,32.0,5180.0,4.3,10,0,True,False,False

In [115]:
y.head()

0     78990
1     79000
2     47990
3     53550
4    129990
Name: price, dtype: int64

In [116]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
#0 and 1

In [117]:
columns_to_normalize = ["Диагональ", "RAM", "Память", "Емкость акк", 'reviews', 'rating','name','Color']

X_norm = X.copy()
X_norm[columns_to_normalize] = scaler.fit_transform(X[columns_to_normalize])
#normalization

In [118]:
X_norm

,name,NFC,Color,Диагональ,RAM,Память,Емкость акк,rating,reviews,OS,Тип экрана_IPS,Тип экрана_OLED,Тип экрана_Other
0,0.212441,0,1.000000,0.542986,0.043478,0.055118,0.049327,0.00,0.00000,0,True,False,False
1,0.212441,0,0.761905,0.542986,0.043478,0.055118,0.049327,0.00,0.00000,0,True,False,False
2,0.213615,0,1.000000,0.452489,0.043478,0.007874,0.022422,0.00,0.00000,0,True,False,False
3,0.213615,0,0.761905,0.452489,0.043478,0.007874,0.022422,0.00,0.00000,0,True,False,False
4,0.203052,1,0.571429,0.723982,0.304348,0.244094,0.381166,0.98,0.02924,0,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3031,0.220657,1,1.000000,0.776471,0.304348,0.244094,0.156951,1.00,0.02924,0,True,False,False
3032,0.220657,1,0.333333,0.776471,0.217391,0.118110,0.156951,0.94,0.02924,0,True,False,False
3033,0.219484,0,0.761905,0.727059,0.130435,0.055118,0.134529,0.00,0.00000,0,True,False,False
3034,0.219484,0,0.761905,0.727059,0.130435,0.118110,0.134529,0.00,0.00000,0,True,False,False
3035,0.219484,0,1.000000,0.727059,0.130435,0.055118,0.134529,0.00,0.00000,0,True,False,False

In [119]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.8, random_state=42)

In [120]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r_squared = r2_score(y_test, y_pred)
print(f'Mean Absolute Error (MAE): {mae}')
print(f'Mean Squared Error (MSE): {mse}')
print(f'R-squared: {r_squared}')
#

Mean Absolute Error (MAE): 93136.83639900485
Mean Squared Error (MSE): 14351798568.100779
R-squared: 0.802340387713459

### *Random forest*

In [121]:
rf = pd.read_csv('before_norm.csv', index_col=0)

In [122]:
rf

,name,price,NFC,Color,Тип экрана,Диагональ,RAM,Память,Емкость акк,rating,reviews,OS
0,CORN C55 Pro,78990,0,черный,IPS,5.500,2.0,64.0,2600.0,0.0,0.000000,0
1,CORN C55 Pro,79000,0,синий,IPS,5.500,2.0,64.0,2600.0,0.0,0.000000,0
2,CORN X50,47990,0,черный,IPS,5.000,2.0,16.0,2000.0,0.0,0.000000,0
3,CORN X50,53550,0,синий,IPS,5.000,2.0,16.0,2000.0,0.0,0.000000,0
4,Blackview BV8900,129990,1,оранжевый,IPS,6.500,8.0,256.0,10000.0,4.9,10.566306,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3031,Coolpad CP12S,99000,1,черный,IPS,6.790,8.0,256.0,5000.0,5.0,10.566306,0
3032,Coolpad CP12S,79000,1,зеленый,IPS,6.790,6.0,128.0,5000.0,4.7,10.566306,0
3033,Coolpad CP12,54900,0,синий,IPS,6.517,4.0,64.0,4500.0,0.0,0.000000,0
3034,Coolpad CP12,59000,0,синий,IPS,6.517,4.0,128.0,4500.0,0.0,0.000000,0
3035,Coolpad CP12,54900,0,черный,IPS,6.517,4.0,64.0,4500.0,0.0,0.000000,0

In [123]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [124]:
rf['name'] = label_encoder.fit_transform(rf['name'])
rf['Color'] = label_encoder.fit_transform(rf['Color'])

In [125]:
rf = pd.get_dummies(rf, columns=['Тип экрана'], drop_first=True)

In [126]:
rf
#wanna check the random forest without normalization

,name,price,NFC,Color,Диагональ,RAM,Память,Емкость акк,rating,reviews,OS,Тип экрана_IPS,Тип экрана_OLED,Тип экрана_Other
0,181,78990,0,21,5.500,2.0,64.0,2600.0,0.0,0.000000,0,True,False,False
1,181,79000,0,16,5.500,2.0,64.0,2600.0,0.0,0.000000,0,True,False,False
2,182,47990,0,21,5.000,2.0,16.0,2000.0,0.0,0.000000,0,True,False,False
3,182,53550,0,16,5.000,2.0,16.0,2000.0,0.0,0.000000,0,True,False,False
4,173,129990,1,12,6.500,8.0,256.0,10000.0,4.9,10.566306,0,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3031,188,99000,1,21,6.790,8.0,256.0,5000.0,5.0,10.566306,0,True,False,False
3032,188,79000,1,7,6.790,6.0,128.0,5000.0,4.7,10.566306,0,True,False,False
3033,187,54900,0,16,6.517,4.0,64.0,4500.0,0.0,0.000000,0,True,False,False
3034,187,59000,0,16,6.517,4.0,128.0,4500.0,0.0,0.000000,0,True,False,False
3035,187,54900,0,21,6.517,4.0,64.0,4500.0,0.0,0.000000,0,True,False,False

In [127]:
y = rf['price']
X = rf.drop('price', axis=1)

In [128]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=42)

In [129]:
from sklearn.ensemble import RandomForestRegressor

model_rf = RandomForestRegressor(n_estimators=100, random_state=42)

model_rf.fit(X_train, y_train)

y_pred_rf = model_rf.predict(X_test)

mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
r_squared_rf = r2_score(y_test, y_pred_rf)

print(f"Random Forest Regression:")
print(f"MAE: {mae_rf}")
print(f"MSE: {mse_rf}")
print(f"R-squared: {r_squared_rf}")

Random Forest Regression:
MAE: 46111.67764512145
MSE: 5538510912.189509
R-squared: 0.9237210643423192

### *Decision Tree*

In [130]:
from sklearn.tree import DecisionTreeRegressor

model_dt = DecisionTreeRegressor(random_state=42)

model_dt.fit(X_train, y_train)

y_pred_dt = model_dt.predict(X_test)

mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
r_squared_dt = r2_score(y_test, y_pred_dt)

print("Decision Tree Regression:")
print(f"MAE: {mae_dt}")
print(f"MSE: {mse_dt}")
print(f"R-squared: {r_squared_dt}")

Decision Tree Regression:
MAE: 54416.31947303417
MSE: 9132076203.432688
R-squared: 0.8742288199505771

### *XGboost*

In [131]:
import xgboost as xgb

In [132]:
y = rf['price']
X = rf.drop('price', axis=1)

In [133]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [134]:
xgb_model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)
xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)
mse_xgb = mean_squared_error(y_test, y_pred_xgb)
mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
r2_xgb = r2_score(y_test, y_pred_xgb)

print(f"XGBoost Metrics:")
print(f"Mean Squared Error (MSE): {mse_xgb:.2f}")
print(f"Mean Absolute Error (MAE): {mae_xgb:.2f}")
print(f"R-squared (R²): {r2_xgb:.2f}")

XGBoost Metrics:
Mean Squared Error (MSE): 3965306159.85
Mean Absolute Error (MAE): 35748.26
R-squared (R²): 0.95

### *Catboost*

In [135]:
from catboost import CatBoostRegressor
catboost_model = CatBoostRegressor(
    iterations=1000,               
    learning_rate=0.1,             
    depth=6,                       
    random_state=42,            
    cat_features=[],              
    verbose=200                    
)
catboost_model.fit(X_train, y_train)
y_pred_catboost = catboost_model.predict(X_test)

mse_catboost = mean_squared_error(y_test, y_pred_catboost)
mae_catboost = mean_absolute_error(y_test, y_pred_catboost)
r2_catboost = r2_score(y_test, y_pred_catboost)
print(f"CatBoost Metrics:")
print(f"Mean Squared Error (MSE): {mse_catboost:.2f}")
print(f"Mean Absolute Error (MAE): {mae_catboost:.2f}")
print(f"R-squared (R²): {r2_catboost:.2f}")

0:	learn: 247859.8816658	total: 1.3ms	remaining: 1.3s
200:	learn: 47188.0659025	total: 216ms	remaining: 860ms
400:	learn: 36888.9574477	total: 427ms	remaining: 638ms
600:	learn: 31385.4874512	total: 643ms	remaining: 427ms
800:	learn: 27366.6973243	total: 860ms	remaining: 214ms
999:	learn: 24512.9443011	total: 1.07s	remaining: 0us
CatBoost Metrics:
Mean Squared Error (MSE): 3635709432.67
Mean Absolute Error (MAE): 34222.87
R-squared (R²): 0.95